from datetime import datetime

from app.services.apple_reviews import fetch_reviews
from app.services.sentiment import annotate
from app.services.metrics import compute_metrics
from app.services.insights import compute_insights


def generate(app_id: str, app_name: str, limit: int = 100) -> str:
    reviews = fetch_reviews(app_id, limit=limit)
    annotate(reviews)
    metrics = compute_metrics(reviews)
    insights = compute_insights(reviews)

    md = []
    md.append(f"# Review Analysis Report — {app_name.title()}")
    md.append("")
    md.append(f"- **App ID:** `{app_id}`")
    md.append(f"- **Generated:** {datetime.now().strftime('%Y-%m-%d %H:%M')}")
    md.append(f"- **Reviews analyzed:** {metrics['total_reviews']}")
    md.append("")

    md.append("## Metrics")
    md.append("")
    md.append(f"**Average rating:** ⭐ {metrics['average_rating']} / 5")
    md.append("")
    md.append("### Rating distribution")
    md.append("")
    md.append("| Stars | Count | Percent |")
    md.append("|---|---|---|")
    for star in range(5, 0, -1):
        row = metrics["rating_distribution"][star]
        bar = "█" * int(row["percent"] / 2)
        md.append(f"| {'⭐' * star} | {row['count']} | {row['percent']}% {bar} |")
    md.append("")

    md.append("### Sentiment distribution")
    md.append("")
    md.append("| Sentiment | Count | Percent |")
    md.append("|---|---|---|")
    for s in ["positive", "neutral", "negative"]:
        row = metrics["sentiment_distribution"][s]
        md.append(f"| {s.title()} | {row['count']} | {row['percent']}% |")
    md.append("")

    md.append("## Top keywords in negative reviews")
    md.append("")
    md.append("Words ranked by TF-IDF (importance, not just frequency):")
    md.append("")
    for kw, score in insights["negative_keywords"][:10]:
        md.append(f"- **{kw}** ({score:.2f})")
    md.append("")

    md.append("## Top phrases in negative reviews")
    md.append("")
    for phrase, count in insights["negative_bigrams"][:10]:
        md.append(f"- *\"{phrase}\"* ({count} mentions)")
    md.append("")

    md.append("## Themes (semantic, via sentence embeddings)")
    md.append("")
    md.append("Reviews classified by meaning, not just keywords:")
    md.append("")
    for theme, data in sorted(insights["themes_semantic"].items(), key=lambda x: -x[1]["count"]):
        md.append(f"### {theme.title()} — {data['count']} reviews")
        md.append("")
        for ex in data["examples"][:2]:
            md.append(f"> *\"{ex['review']}\"*")
            md.append(f">  — cosine similarity: {ex['score']}")
            md.append("")

    md.append("## Themes (rule-based, for comparison)")
    md.append("")
    md.append("Keyword-matching against hardcoded theme vocabulary:")
    md.append("")
    for theme in insights["themes_rule_based"]:
        evidence = ", ".join(f"{w} ({s:.1f})" for w, s in theme["evidence"][:5])
        md.append(f"- **{theme['theme'].title()}** (weight {theme['weight']:.1f}) — {evidence}")
    md.append("")

    md.append("## Actionable recommendations")
    md.append("")
    md.append("Generated by Claude Haiku from the analysis above:")
    md.append("")
    for rec in insights["recommendations"]:
        md.append(f"- {rec}")
    md.append("")

    md.append("## Sample reviews")
    md.append("")
    negatives = sorted([r for r in reviews if r.sentiment == "negative"], key=lambda r: r.rating)[:3]
    for r in negatives:
        md.append(f"### {'⭐' * r.rating} — *{r.title}*")
        md.append(f"by {r.author or 'anonymous'}")
        md.append("")
        md.append(f"> {r.content}")
        md.append("")
        md.append(f"**Sentiment:** {r.sentiment}")
        md.append("")
        md.append("---")
        md.append("")

    md.append("## Methodology")
    md.append("")
    md.append("- **Source:** Apple iTunes RSS customer reviews feed")
    md.append("- **Sentiment:** VADER lexicon-based scoring on title + content, with rating-based override for extreme mismatches")
    md.append("- **Keywords:** TF-IDF over lemmatized tokens, stopwords from NLTK + domain-specific")
    md.append("- **Bigrams:** sklearn CountVectorizer with `min_df=2`")
    md.append("- **Themes (rule-based):** keyword matching against hardcoded vocabulary")
    md.append("- **Themes (semantic):** sentence-transformers `all-MiniLM-L6-v2` + cosine similarity, multi-assign with per-theme thresholds")
    md.append("- **Recommendations:** Claude Haiku 4.5 prompted with themes + bigrams")

    return "\n".join(md)

if __name__ == "__main__":
    app_id = "547702041"
    app_name = "tinder"
    limit = 100

    report = generate(app_id, app_name, limit)
    print(report)
